# Permalinks
#
permalink:           pretty

# Setup
title:               Colorsublime
tagline:             Color your Sublime Text editor trying your favorite theme online before downloading it for free
baseurl:
# Handling Reading
encoding:           "utf-8"
markdown_ext:       "markdown,md"

plugins:
  - jekyll-paginate-v2
  - jekyll-lunr-js-search

exclude: [node_modules,build,Makefile]

# Assets
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:         assets/css
  style:            :compressed

collections:
  themes:
    output: true

# Pagination Settings
pagination:
  enabled: true
  per_page: 9
  permalink: '/page/:num/'
  limit: 0

github_download_base_url: https://raw.githubusercontent.com/Colorsublime/Colorsublime-Themes/master/themes/

lunr_search:
  js_dir: assets/js